server:
  port: 80

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

#消费者将要去访问的微服务名称(注册成功进nacos的微服务提供者)
#定义该属性用于代码中的配置分离
service-url:
  nacos-user-service: http://nacos-payment-provider